from __future__ import annotations

from collections.abc import Iterable

from fastapi.routing import APIRoute


def _routes() -> dict[str, set[str]]:
    from francis.api.app import create_app

    app = create_app()
    out: dict[str, set[str]] = {}
    for route in app.routes:
        if not isinstance(route, APIRoute):
            continue
        methods = {method.upper() for method in (route.methods or set())}
        out.setdefault(route.path, set()).update(methods)
    return out


def _assert_has_endpoints(routes: dict[str, set[str]], endpoints: Iterable[tuple[str, str]]) -> None:
    missing: list[str] = []
    for method, path in endpoints:
        methods = routes.get(path)
        if methods is None:
            missing.append(f"{method} {path} (path missing)")
            continue
        if method.upper() not in methods:
            missing.append(f"{method} {path} (method missing; have {sorted(methods)})")
    assert not missing, "Missing chat-ui contract endpoints:\n" + "\n".join(missing)


def test_chat_ui_contract_endpoints_are_mounted() -> None:
    routes = _routes()

    endpoints = [
        ("POST", "/chat/send"),
        ("GET", "/approvals/list"),
        ("POST", "/approvals/decision"),
        ("GET", "/continuity/ledger"),
        ("GET", "/continuity/briefing"),
        ("GET", "/continuity/shift_briefing"),
        ("GET", "/continuity/shift-briefing"),
        ("GET", "/credentials/list"),
        ("GET", "/credentials/scopes"),
        ("GET", "/credentials/delegations"),
        ("POST", "/credentials/request"),
        ("POST", "/credentials/revoke"),
        ("GET", "/domains/list"),
        ("GET", "/domains/get"),
        ("POST", "/domains/create"),
        ("PATCH", "/domains/update"),
        ("POST", "/domains/delete"),
        ("GET", "/domains/summary"),
        ("GET", "/explanations/list"),
        ("GET", "/explanations/get"),
        ("GET", "/explanations/export"),
        ("GET", "/federation/instances/list"),
        ("GET", "/federation/instances/get"),
        ("GET", "/federation/delegations/list"),
        ("GET", "/federation/consensus_logs/list"),
        ("GET", "/federation/shared_knowledge/list"),
        ("GET", "/industrial/digital_twins/list"),
        ("GET", "/industrial/digital_twins/get"),
        ("GET", "/industrial/digital_twins/snapshot"),
        ("POST", "/industrial/digital_twins/action"),
        ("GET", "/industrial/assets"),
        ("POST", "/industrial/assets"),
        ("PATCH", "/industrial/assets/{asset_id}"),
        ("DELETE", "/industrial/assets/{asset_id}"),
        ("GET", "/industrial/processes"),
        ("POST", "/industrial/processes"),
        ("GET", "/industrial/simulations"),
        ("POST", "/industrial/simulations"),
        ("GET", "/industrial/runs"),
        ("POST", "/industrial/runs/start"),
        ("POST", "/industrial/runs/{run_id}/cancel"),
        ("GET", "/industrial/runs/export"),
        ("GET", "/industrial/safety/validations"),
        ("POST", "/industrial/safety/validate"),
        ("GET", "/industrial/telemetry"),
        ("POST", "/industrial/interventions/request"),
        ("POST", "/industrial/interventions/execute"),
        ("GET", "/lens/status"),
        ("GET", "/lens/hud"),
        ("GET", "/lens/preflight"),
        ("GET", "/lens/host/activation"),
        ("GET", "/lens/host/activation/denials"),
        ("GET", "/lens/host/activation/plan"),
        ("GET", "/lens/host/activation/preflight"),
        ("POST", "/lens/host/activation/execute"),
        ("POST", "/lens/host/activation/request"),
        ("GET", "/memory/timeline/list"),
        ("GET", "/memory/timeline/get"),
        ("GET", "/memory/timeline/export"),
        ("GET", "/missions/list"),
        ("GET", "/missions/queue"),
        ("POST", "/missions/create"),
        ("POST", "/missions/run_once"),
        ("POST", "/missions/tick"),
        ("GET", "/missions/{mission_id}"),
        ("PATCH", "/missions/{mission_id}"),
        ("POST", "/missions/{mission_id}/tick"),
        ("POST", "/missions/{mission_id}/deadletter"),
        ("POST", "/missions/{mission_id}/advance"),
        ("GET", "/operations/list"),
        ("POST", "/operations/get_many"),
        ("POST", "/operations/create"),
        ("POST", "/operations/run-once"),
        ("GET", "/operations/{operation_id}"),
        ("PATCH", "/operations/{operation_id}"),
        ("POST", "/operations/{operation_id}/run"),
        ("POST", "/operations/{operation_id}/cancel"),
        ("DELETE", "/operations/{operation_id}"),
        ("GET", "/operations/export"),
        ("GET", "/reactor/review_queue"),
        ("GET", "/forge/proposals/list"),
        ("POST", "/forge/proposals/decision"),
        ("GET", "/forge/proposal_reviews/list"),
        ("GET", "/forge/promotions/list"),
        ("GET", "/forge/promotion_readiness/list"),
        ("GET", "/plugins/list"),
        ("GET", "/plugins/get"),
        ("GET", "/plugins/capabilities/catalog"),
        ("POST", "/plugins/enable"),
        ("POST", "/plugins/disable"),
        ("POST", "/plugins/install"),
        ("POST", "/plugins/uninstall"),
        ("POST", "/plugins/run"),
        ("POST", "/plugins/reload"),
        ("GET", "/plugins/tools/list"),
        ("GET", "/plugins/tools/get"),
        ("GET", "/plugins/tools/export"),
        ("POST", "/plugins/tools/run"),
        ("GET", "/system/info"),
        ("GET", "/system/status"),
        ("GET", "/system/health"),
        ("GET", "/system/world_state"),
        ("GET", "/system/world-state"),
        ("GET", "/system/orb_status"),
        ("GET", "/system/orb-status"),
        ("GET", "/system/orb"),
        ("GET", "/system/operator_mode"),
        ("GET", "/system/operator-mode"),
        ("POST", "/system/operator_mode"),
        ("POST", "/system/operator-mode"),
        ("POST", "/system/observer/scan"),
        ("GET", "/system/observer/events"),
        ("GET", "/system/observer/log"),
        ("GET", "/system/observer/audit"),
        ("GET", "/system/flags"),
        ("GET", "/system/feature_flags"),
        ("GET", "/system/features"),
        ("GET", "/system/config/effective"),
        ("GET", "/system/effective_config"),
        ("GET", "/system/config"),
        ("POST", "/system/config/mutate"),
        ("POST", "/system/config/patch"),
        ("POST", "/system/settings/mutate"),
        ("POST", "/system/settings"),
        ("POST", "/system/flags/set"),
        ("POST", "/system/flags/{key}"),
        ("POST", "/system/feature_flags/set"),
        ("POST", "/system/feature_flags/{key}"),
        ("GET", "/trust/state"),
        ("GET", "/trust/history"),
        ("GET", "/trust/events"),
        ("GET", "/trust/policy"),
        ("POST", "/trust/adjust"),
        ("GET", "/system/trust/state"),
        ("GET", "/system/trust/history"),
        ("GET", "/system/trust/events"),
        ("GET", "/system/trust/policy"),
        ("POST", "/system/trust/adjust"),
        ("GET", "/web_learning/status"),
        ("GET", "/web_learning/policy"),
        ("GET", "/web_learning/records"),
        ("GET", "/web_learning/events"),
        ("GET", "/web_learning/quarantine"),
        ("POST", "/web_learning/request"),
        ("POST", "/web_learning/enabled"),
        ("POST", "/web_learning/quarantine/decide"),
        ("GET", "/web_learning/records/export"),
        ("POST", "/web_learning/export"),
        ("GET", "/web-learning/status"),
        ("GET", "/system/web_learning/policy"),
        ("GET", "/system/web-learning/policy"),
        ("POST", "/system/web-learning/request"),
        ("GET", "/telemetry/status"),
        ("GET", "/telemetry/context"),
        ("GET", "/telemetry/context/feedback"),
        ("GET", "/telemetry/context/feedback/memory-assistance-chat-context-contract"),
        ("GET", "/telemetry/context/feedback/memory-assistance-chat-context-readback"),
        ("GET", "/telemetry/context/feedback/memory-assistance-dry-run"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-audit"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-e2e-acceptance-audit"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-e2e-sample"),
        (
            "GET",
            "/telemetry/context/feedback/memory-assistance-feedback-loop-live-sample-operator-decision-outcome-review",
        ),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-action-quality-signal-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-git-context-signal"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-ide-context-signal"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-memory-poisoning-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-operator-context-surface-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-primary-loop-evidence-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-sensing-indicator-summary"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-terminal-context-signal"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-true-execution-trace-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-live-sample-operator-decisions"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-live-sample-operator-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-memory-quality"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-memory-readback"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-policy"),
        ("GET", "/telemetry/context/feedback/memory-quality"),
        ("GET", "/telemetry/context/feedback/memory-retrieval-policy"),
        ("GET", "/telemetry/context/feedback/memory-retrieval-readback"),
        ("GET", "/telemetry/context/feedback/review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-live-sample-readback"),
        ("POST", "/telemetry/context/feedback/memory-assistance-feedback-loop-live-sample-operator-decision"),
        ("POST", "/telemetry/context/feedback/memory-assistance-feedback-memory-quality"),
        ("POST", "/telemetry/context/feedback/memory-quality"),
        ("POST", "/telemetry/context/feedback"),
        ("GET", "/telemetry/git/status"),
        ("GET", "/telemetry/ide-diagnostics/scope"),
        ("GET", "/telemetry/ide-diagnostics/events"),
        ("POST", "/telemetry/ide-diagnostics/events"),
        ("GET", "/telemetry/terminal/scope"),
        ("GET", "/telemetry/terminal/events"),
        ("POST", "/telemetry/terminal/events"),
    ]
    _assert_has_endpoints(routes, endpoints)
