from __future__ import annotations

from collections.abc import Iterable

from fastapi.routing import APIRoute


def _routes() -> dict[str, set[str]]:
    from francis.api.app import create_app

    app = create_app()
    out: dict[str, set[str]] = {}
    for route in app.routes:
        if not isinstance(route, APIRoute):
            continue
        methods = {method.upper() for method in (route.methods or set())}
        out.setdefault(route.path, set()).update(methods)
    return out


def _assert_has_endpoints(routes: dict[str, set[str]], endpoints: Iterable[tuple[str, str]]) -> None:
    missing: list[str] = []
    for method, path in endpoints:
        methods = routes.get(path)
        if methods is None:
            missing.append(f"{method} {path} (path missing)")
            continue
        if method.upper() not in methods:
            missing.append(f"{method} {path} (method missing; have {sorted(methods)})")
    assert not missing, "Missing chat-ui contract endpoints:\n" + "\n".join(missing)


def test_chat_ui_contract_endpoints_are_mounted() -> None:
    routes = _routes()

    endpoints = [
        ("POST", "/chat/send"),
        ("GET", "/approvals/list"),
        ("POST", "/approvals/decision"),
        ("GET", "/continuity/ledger"),
        ("GET", "/continuity/briefing"),
        ("GET", "/continuity/shift_briefing"),
        ("GET", "/continuity/shift-briefing"),
        ("GET", "/credentials/list"),
        ("GET", "/credentials/scopes"),
        ("GET", "/credentials/delegations"),
        ("POST", "/credentials/request"),
        ("POST", "/credentials/revoke"),
        ("GET", "/domains/list"),
        ("GET", "/domains/get"),
        ("POST", "/domains/create"),
        ("PATCH", "/domains/update"),
        ("POST", "/domains/delete"),
        ("GET", "/domains/summary"),
        ("GET", "/explanations/list"),
        ("GET", "/explanations/get"),
        ("GET", "/explanations/export"),
        ("GET", "/federation/status"),
        ("GET", "/federation/pairing-scoped-trust-contract"),
        ("GET", "/federation/sync-model-contract"),
        ("GET", "/federation/remote-approval-contract"),
        ("GET", "/federation/revocation-contract"),
        ("GET", "/federation/node-attributed-continuity-contract"),
        ("GET", "/federation/completion-review"),
        ("GET", "/federation/sleep-continuity-runbook"),
        ("GET", "/federation/sleep-continuity-action"),
        ("GET", "/federation/sleep-resume-confirmations"),
        ("GET", "/federation/sleep-resume-confirmation/actor-readiness"),
        ("GET", "/federation/sleep-resume-confirmation/operator-checklist"),
        ("GET", "/federation/sleep-resume-confirmation/receipt-backed-sequence-readiness"),
        ("GET", "/federation/stage-closure-decisions"),
        ("GET", "/federation/live-runtime-readbacks"),
        ("POST", "/federation/sleep-resume-confirmation"),
        ("POST", "/federation/stage-closure-decision"),
        ("POST", "/federation/live-runtime-readback"),
        ("GET", "/managed-copies/status"),
        ("GET", "/managed-copies/copy-creation-contract"),
        ("GET", "/managed-copies/isolation-rules-contract"),
        ("GET", "/managed-copies/safe-delta-model-contract"),
        ("GET", "/federation/instances/list"),
        ("GET", "/federation/instances/get"),
        ("GET", "/federation/delegations/list"),
        ("GET", "/federation/consensus_logs/list"),
        ("GET", "/federation/shared_knowledge/list"),
        ("GET", "/industrial/digital_twins/list"),
        ("GET", "/industrial/digital_twins/get"),
        ("GET", "/industrial/digital_twins/snapshot"),
        ("POST", "/industrial/digital_twins/action"),
        ("GET", "/industrial/assets"),
        ("POST", "/industrial/assets"),
        ("PATCH", "/industrial/assets/{asset_id}"),
        ("DELETE", "/industrial/assets/{asset_id}"),
        ("GET", "/industrial/processes"),
        ("POST", "/industrial/processes"),
        ("GET", "/industrial/simulations"),
        ("POST", "/industrial/simulations"),
        ("GET", "/industrial/runs"),
        ("POST", "/industrial/runs/start"),
        ("POST", "/industrial/runs/{run_id}/cancel"),
        ("GET", "/industrial/runs/export"),
        ("GET", "/industrial/safety/validations"),
        ("POST", "/industrial/safety/validate"),
        ("GET", "/industrial/telemetry"),
        ("POST", "/industrial/interventions/request"),
        ("POST", "/industrial/interventions/execute"),
        ("GET", "/lens/status"),
        ("GET", "/lens/hud"),
        ("GET", "/lens/preflight"),
        ("GET", "/lens/host/activation"),
        ("GET", "/lens/host/activation/denials"),
        ("GET", "/lens/host/activation/plan"),
        ("GET", "/lens/host/activation/preflight"),
        ("POST", "/lens/host/activation/execute"),
        ("POST", "/lens/host/activation/request"),
        ("GET", "/memory/timeline/list"),
        ("GET", "/memory/timeline/get"),
        ("GET", "/memory/timeline/export"),
        ("GET", "/missions/list"),
        ("GET", "/missions/queue"),
        ("POST", "/missions/create"),
        ("POST", "/missions/run_once"),
        ("POST", "/missions/tick"),
        ("GET", "/missions/{mission_id}"),
        ("PATCH", "/missions/{mission_id}"),
        ("POST", "/missions/{mission_id}/tick"),
        ("POST", "/missions/{mission_id}/deadletter"),
        ("POST", "/missions/{mission_id}/advance"),
        ("GET", "/operations/list"),
        ("POST", "/operations/get_many"),
        ("POST", "/operations/create"),
        ("POST", "/operations/run-once"),
        ("GET", "/operations/{operation_id}"),
        ("PATCH", "/operations/{operation_id}"),
        ("POST", "/operations/{operation_id}/run"),
        ("POST", "/operations/{operation_id}/cancel"),
        ("DELETE", "/operations/{operation_id}"),
        ("GET", "/operations/export"),
        ("GET", "/reactor/review_queue"),
        ("GET", "/forge/proposals/list"),
        ("POST", "/forge/proposals/decision"),
        ("GET", "/forge/proposal_reviews/list"),
        ("GET", "/forge/promotions/list"),
        ("GET", "/forge/promotion_readiness/list"),
        ("GET", "/plugins/list"),
        ("GET", "/plugins/get"),
        ("GET", "/plugins/capabilities/catalog"),
        ("GET", "/plugins/capabilities/packs/migration/plan"),
        ("GET", "/plugins/capabilities/packs/quality/standards"),
        ("GET", "/plugins/capabilities/packs/quality/tests"),
        ("GET", "/plugins/capabilities/packs/quality/docs"),
        ("GET", "/plugins/capabilities/packs/quality/evidence/remediation"),
        ("POST", "/plugins/capabilities/packs/quality/evidence/remediation/apply"),
        ("GET", "/plugins/capabilities/packs/validation/receipts"),
        ("GET", "/plugins/capabilities/packs/lineage/proposals"),
        ("GET", "/plugins/capabilities/packs/promotion/receipts"),
        ("GET", "/plugins/capabilities/packs/promotion/discipline"),
        ("GET", "/plugins/capabilities/packs/operator/review"),
        ("GET", "/plugins/capabilities/packs/operator/review/decisions"),
        ("POST", "/plugins/capabilities/packs/operator/review/decisions"),
        ("POST", "/plugins/capabilities/packs/operator/review/decisions/bulk-from-surface"),
        ("GET", "/plugins/capabilities/library/operator/surface"),
        ("GET", "/plugins/capabilities/library/promotion/plan"),
        ("GET", "/plugins/capabilities/library/proposal-evidence/plan"),
        ("GET", "/plugins/capabilities/library/proposal-evidence/source-readiness"),
        ("GET", "/plugins/capabilities/library/proposal-evidence/remediation"),
        ("POST", "/plugins/capabilities/library/proposal-evidence/remediation/apply"),
        ("GET", "/plugins/capabilities/library/proposal-evidence/friction-summary-refs"),
        ("POST", "/plugins/capabilities/library/proposal-evidence/friction-summary-refs/apply"),
        ("GET", "/plugins/capabilities/library/proposal-evidence/operator-intake/checklist"),
        ("GET", "/plugins/capabilities/library/proposal-evidence/operator-intake/worksheet"),
        ("GET", "/plugins/capabilities/library/proposal-evidence/operator-intake/export"),
        ("POST", "/plugins/capabilities/library/proposal-evidence/operator-intake/import-preview"),
        ("GET", "/plugins/capabilities/library/proposal-evidence/operator-intake/audit"),
        ("POST", "/plugins/capabilities/library/proposal-evidence/operator-intake/preview"),
        ("POST", "/plugins/capabilities/library/proposal-evidence/operator-intake/apply"),
        ("GET", "/plugins/capabilities/library/proposal-review/plan"),
        ("GET", "/plugins/capabilities/library/proposal-review/apply-readiness"),
        ("GET", "/plugins/capabilities/packs/promotion/rules"),
        ("GET", "/plugins/capabilities/packs/promotion/rules/remediation"),
        ("POST", "/plugins/capabilities/packs/promotion/rules/remediation/apply"),
        ("GET", "/plugins/capabilities/packs/metadata/receipts"),
        ("POST", "/plugins/capabilities/packs/metadata/receipts"),
        ("POST", "/plugins/capabilities/packs/metadata/receipts/bulk-from-plan"),
        ("POST", "/plugins/enable"),
        ("POST", "/plugins/disable"),
        ("POST", "/plugins/install"),
        ("POST", "/plugins/uninstall"),
        ("POST", "/plugins/run"),
        ("POST", "/plugins/reload"),
        ("GET", "/plugins/tools/list"),
        ("GET", "/plugins/tools/get"),
        ("GET", "/plugins/tools/export"),
        ("POST", "/plugins/tools/run"),
        ("GET", "/system/info"),
        ("GET", "/system/status"),
        ("GET", "/system/health"),
        ("GET", "/system/world_state"),
        ("GET", "/system/world-state"),
        ("GET", "/system/orb_status"),
        ("GET", "/system/orb-status"),
        ("GET", "/system/orb"),
        ("GET", "/system/operator_mode"),
        ("GET", "/system/operator-mode"),
        ("POST", "/system/operator_mode"),
        ("POST", "/system/operator-mode"),
        ("POST", "/system/observer/scan"),
        ("GET", "/system/observer/events"),
        ("GET", "/system/observer/log"),
        ("GET", "/system/observer/audit"),
        ("GET", "/system/flags"),
        ("GET", "/system/feature_flags"),
        ("GET", "/system/features"),
        ("GET", "/system/config/effective"),
        ("GET", "/system/effective_config"),
        ("GET", "/system/config"),
        ("POST", "/system/config/mutate"),
        ("POST", "/system/config/patch"),
        ("POST", "/system/settings/mutate"),
        ("POST", "/system/settings"),
        ("POST", "/system/flags/set"),
        ("POST", "/system/flags/{key}"),
        ("POST", "/system/feature_flags/set"),
        ("POST", "/system/feature_flags/{key}"),
        ("GET", "/trust/state"),
        ("GET", "/trust/history"),
        ("GET", "/trust/events"),
        ("GET", "/trust/policy"),
        ("POST", "/trust/adjust"),
        ("GET", "/system/trust/state"),
        ("GET", "/system/trust/history"),
        ("GET", "/system/trust/events"),
        ("GET", "/system/trust/policy"),
        ("POST", "/system/trust/adjust"),
        ("GET", "/web_learning/status"),
        ("GET", "/web_learning/policy"),
        ("GET", "/web_learning/records"),
        ("GET", "/web_learning/events"),
        ("GET", "/web_learning/quarantine"),
        ("POST", "/web_learning/request"),
        ("POST", "/web_learning/enabled"),
        ("POST", "/web_learning/quarantine/decide"),
        ("GET", "/web_learning/records/export"),
        ("POST", "/web_learning/export"),
        ("GET", "/web-learning/status"),
        ("GET", "/system/web_learning/policy"),
        ("GET", "/system/web-learning/policy"),
        ("POST", "/system/web-learning/request"),
        ("GET", "/telemetry/status"),
        ("GET", "/telemetry/context"),
        ("GET", "/telemetry/context/feedback"),
        ("GET", "/telemetry/context/feedback/memory-assistance-chat-context-contract"),
        ("GET", "/telemetry/context/feedback/memory-assistance-chat-context-readback"),
        ("GET", "/telemetry/context/feedback/memory-assistance-dry-run"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-audit"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-done-criteria-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-e2e-acceptance-audit"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-e2e-sample"),
        (
            "GET",
            "/telemetry/context/feedback/memory-assistance-feedback-loop-live-sample-operator-decision-outcome-review",
        ),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-action-quality-signal-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-git-context-signal"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-ide-context-signal"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-memory-poisoning-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-multi-source-usefulness-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-closure-readiness-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-operator-usage-over-time-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-memory-write-contract-hardening-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-memory-contract-operator-surface-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-stage-closure-decisions"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-operator-context-surface-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-primary-loop-evidence-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-sensing-indicator-summary"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-terminal-context-signal"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-true-execution-trace-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-live-sample-operator-decisions"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-live-sample-operator-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-memory-quality"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-memory-readback"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-policy"),
        ("GET", "/telemetry/context/feedback/memory-quality"),
        ("GET", "/telemetry/context/feedback/memory-retrieval-policy"),
        ("GET", "/telemetry/context/feedback/memory-retrieval-readback"),
        ("GET", "/telemetry/context/feedback/review"),
        ("GET", "/telemetry/context/feedback/memory-assistance-feedback-loop-live-sample-readback"),
        ("POST", "/telemetry/context/feedback/memory-assistance-feedback-loop-live-sample-run"),
        ("POST", "/telemetry/context/feedback/memory-assistance-feedback-loop-stage-closure-decision"),
        ("POST", "/telemetry/context/feedback/memory-assistance-feedback-loop-live-sample-operator-decision"),
        ("POST", "/telemetry/context/feedback/memory-assistance-feedback-memory-quality"),
        ("POST", "/telemetry/context/feedback/memory-quality"),
        ("POST", "/telemetry/context/feedback"),
        ("GET", "/telemetry/git/status"),
        ("GET", "/telemetry/ide-diagnostics/scope"),
        ("GET", "/telemetry/ide-diagnostics/events"),
        ("POST", "/telemetry/ide-diagnostics/events"),
        ("GET", "/telemetry/terminal/scope"),
        ("GET", "/telemetry/terminal/events"),
        ("POST", "/telemetry/terminal/events"),
        ("GET", "/executor/substrate/status"),
        ("GET", "/executor/substrate/toolbelt-allowlist-review"),
        ("GET", "/executor/substrate/branch-first-workflow-review"),
        ("GET", "/executor/substrate/leases-idempotency-review"),
        ("GET", "/executor/substrate/verification-hooks-review"),
        ("GET", "/executor/substrate/scope-enforcement-review"),
        ("GET", "/executor/substrate/stage-closure-decisions"),
        ("POST", "/executor/substrate/stage-closure-decision"),
        ("GET", "/takeover/status"),
        ("GET", "/takeover/action-feed"),
        ("GET", "/takeover/operator-surface-contract"),
        ("GET", "/takeover/completion-review"),
        ("GET", "/takeover/stage-closure-decisions"),
        ("GET", "/takeover/control-transfer-receipts"),
        ("GET", "/takeover/panic-stop-receipts"),
        ("GET", "/takeover/handback-summaries"),
        ("GET", "/takeover/delegated-action-receipts"),
        ("POST", "/takeover/control-transfer"),
        ("POST", "/takeover/delegated-action"),
        ("POST", "/takeover/stage-closure-decision"),
        ("POST", "/takeover/panic-stop"),
        ("POST", "/takeover/handback-summary"),
        ("GET", "/away/status"),
        ("GET", "/away/safe-task-classes"),
        ("GET", "/away/autonomy-budgets"),
        ("GET", "/away/shift-report"),
        ("GET", "/away/return-briefing"),
        ("GET", "/away/completion-review"),
        ("GET", "/away/live-progress-samples"),
        ("GET", "/away/stage-closure-decisions"),
        ("POST", "/away/live-progress-sample"),
        ("POST", "/away/stage-closure-decision"),
        ("GET", "/apprenticeship/status"),
        ("GET", "/apprenticeship/teaching-session-contract"),
        ("GET", "/apprenticeship/replay-generalization-contract"),
        ("GET", "/apprenticeship/skillization-artifact-contract"),
        ("GET", "/apprenticeship/forge-handoff-contract"),
        ("GET", "/apprenticeship/live-teaching-session-ux"),
        ("GET", "/apprenticeship/teaching-session-receipts"),
        ("POST", "/apprenticeship/teaching-session"),
        ("GET", "/apprenticeship/replay-receipts"),
        ("POST", "/apprenticeship/replay-receipt"),
        ("GET", "/apprenticeship/skillization-artifact-receipts"),
        ("POST", "/apprenticeship/skillization-artifact-receipt"),
        ("GET", "/apprenticeship/forge-handoff-receipts"),
        ("POST", "/apprenticeship/forge-handoff-receipt"),
        ("GET", "/apprenticeship/completion-review"),
        ("GET", "/apprenticeship/stage-closure-decisions"),
        ("POST", "/apprenticeship/stage-closure-decision"),
        ("GET", "/knowledge-fabric/status"),
        ("GET", "/knowledge-fabric/artifact-index-contract"),
        ("GET", "/knowledge-fabric/artifact-index-projection"),
        ("GET", "/knowledge-fabric/retrieval-preview"),
        ("GET", "/knowledge-fabric/local-evidence-citations"),
        ("GET", "/knowledge-fabric/retention-model"),
        ("GET", "/knowledge-fabric/completion-review"),
        ("GET", "/knowledge-fabric/stage-closure-decisions"),
        ("POST", "/knowledge-fabric/stage-closure-decision"),
        ("GET", "/trust-calibration/status"),
        ("GET", "/trust-calibration/confidence-rules-contract"),
        ("GET", "/trust-calibration/verification-gate-contract"),
        ("GET", "/trust-calibration/anti-overclaim-policy"),
        ("GET", "/trust-calibration/calibrated-claim-logic"),
        ("GET", "/trust-calibration/ui-state-coherence"),
        ("GET", "/trust-calibration/operator-browser-visual-readbacks"),
        ("GET", "/trust-calibration/completion-review"),
        ("GET", "/trust-calibration/stage-closure-decisions"),
        ("POST", "/trust-calibration/operator-browser-visual-readback"),
        ("POST", "/trust-calibration/stage-closure-decision"),
        ("POST", "/trust-calibration/evaluate-claim"),
        ("GET", "/adversarial-hardening/status"),
        ("GET", "/adversarial-hardening/injection-containment-contract"),
        ("GET", "/adversarial-hardening/quarantine-model-contract"),
        ("GET", "/adversarial-hardening/red-team-regression-suite"),
        ("GET", "/adversarial-hardening/policy-bypass-regression-suite"),
        ("GET", "/adversarial-hardening/completion-review"),
        ("GET", "/adversarial-hardening/stage-closure-decisions"),
        ("POST", "/adversarial-hardening/stage-closure-decision"),
        ("GET", "/swarm/status"),
        ("GET", "/swarm/unit-roles-contract"),
        ("GET", "/swarm/messaging-model-contract"),
        ("GET", "/swarm/delegation-etiquette-contract"),
        ("GET", "/swarm/trace-continuity-contract"),
        ("GET", "/swarm/failure-semantics-contract"),
        ("GET", "/swarm/completion-review"),
        ("GET", "/swarm/stage-closure-decisions"),
        ("POST", "/swarm/stage-closure-decision"),
    ]
    _assert_has_endpoints(routes, endpoints)
